services:
  - type: web
    name: flask-logistics-auth
    env: python
    buildCommand: ""
    startCommand: python app.py
    plan: free
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true